config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :items
  resources :users
  resources :lists
  
  get 'main_pages/home' => 'main_pages#home', :as => :traversal_home
  get 'main_pages/list_results' => 'main_pages#city_search', :as => :city_search
  post 'main_pages/list_results' => 'main_pages#list_results'
  get 'main_pages/add_to_user' => "main_pages#add_to_user", :as => :add_to_user
  
  get 'main_pages/about_us' => 'main_pages#about_us', :as => :traversal_about_us
  get 'main_pages/contact_us' => 'main_pages#contact_us', :as => :traversal_contact_us
  
  resources :main_pages do
  get :autocomplete_city_name_and_cc, :on => :collection
  end

  root :to => 'main_pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user, counter_cache: true, inverse_of: :lists
  
  has_many :items, inverse_of: :list
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :all_lists, only: [:index, :create, :update, :destroy]
  before_action :set_lists, only: [:edit, :update, :destroy]
    respond_to :html, :js
      
    def new
      @list = List.new
      @user = User.find(params[:id])
    end

    def create
      @list  = List.create(list_params)
      @lists = User.find(list_params[:user_id]).lists.order("id ASC")
    end
    
    def destroy
      @list = List.find(params[:id])
      @user_id = @list.user_id
      @list.destroy
      @lists = User.find(@user_id).lists.order("id ASC")
    end
    
    def update
      @list.update_attributes(list_params)
      @lists = User.find(list_params[:user_id]).lists.order("id ASC")
    end

    private

      def all_lists
        @lists = List.all.order("id ASC")
      end
      
      def set_lists
        @list = List.find(params[:id])
        @user = @list.user
      end

      def list_params
        params.require(:list).permit(:description, :name, :user_id)
      end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, remote: true do |f|   %>
  <%= f.label  :name                      %>
  <%= f.text_field  :name, :autofocus => true, id: "list_name"              %>
  <%= f.label  :description %>
  <%= f.text_field  :description                     %>
  <%= f.hidden_field :user_id, :value => @user.id %>
<%= f.submit "Create", :id => "list_new_submit", :class => "hide" %>
<% end %>

app/views/lists/_list.html.erb
<li>
  <div class="collapsible-header">
    <i class="material-icons">filter_drama</i>
  <%= list.name%> - <span class="teal-text text-lighten-2"><%= list.description%></span>
  
  <span class="edit right">
    <%= link_to edit_list_path(list), remote: true do %>
        <i class="small material-icons grey-text text-darken-1">edit</i>
    <% end %>

    <%= link_to list, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } do %>
    <i class="small material-icons grey-text text-darken-1">delete</i>
    <% end %>
  </span>
</div>
  <% @items =  list.items.order("id ASC")  %>  
  <div class="collapsible-body">
      <%= render partial: "items/list_item", :locals => {:list_id => list.id }%>
   <br>
   <%= link_to new_item_path(:list_id => list.id), remote: true do %>
     <button class="waves-effect waves-light btn blue">New Item</button>
   <% end %>
  </div>


</li>

app/views/lists/create.js.erb
$('#lists').html("<%= j (render @lists) %>");
$('#new_list_modal').closeModal();
//$('#list-form').slideUp(350);
Materialize.toast('List Added!', 4000)

app/views/lists/destroy.js.erb
$('#lists').html("<%= escape_javascript(render @lists) %>");
Materialize.toast('List deleted!', 4000) // 4000 is the duration of the toast

app/views/lists/edit.js.erb
$('#list-form').html("<%= j (render 'form',  :formats => :html) %>");
$('#list-content').html("<%= j (render 'form',  :formats => :html) %>");
$('#new_list_modal').openModal();
$('#list_name').focus();

app/views/lists/index.html.erb
  <div id="user--lists" class="col s12 m8 l8">
    <div style="font-size:2rem;">Lists</div>
      <ul id="lists" class="collapsible" data-collapsible="expandable">  
        <%= render @lists %>
       </ul>
      
  <br/>

  <!-- Modal Trigger -->
  <%= link_to new_list_path(:params => params), remote: true do %>
    <button class="waves-effect waves-light btn">New List</button>
  <% end %>

  <!-- Modal Structure -->
  <div id="new_list_modal" class="modal">
    <div class="modal-content">
      <h4>New List Information</h4>
      <p id="list-content">
      
      </p>
    </div>
    <div class="modal-footer">
      <a href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
      <a id="list_new_submit_btn" href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Create</a>
    </div>
  </div>
  
  <div id="new_item_modal" class="modal">
    <div class="modal-content">
      <h4>New Item Information</h4>
      <p id="item-content">
      
      </p>
    </div>
    <div class="modal-footer">
      <a href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
      <a id="item_new_submit_btn" href="#" class="modal-action modal-close waves-effect waves-green btn-flat">Create</a>
    </div>
  </div>
  <!-- insert a jquery code to click the create which is hidden to submit the new listing -->
  
  <!-- legacy purposes -->
  <!--  <div id="list-form" style="display:none;"></div> --> 
  
  </div>
  
  <% content_for :script  do%> <!-- type JS code here to add into js at the footer -->
  $("#list_new_submit_btn").on("click", function(){
    $("#list_new_submit").click();
  });
  
  $("#item_new_submit_btn").on("click", function(){
    $("#item_new_submit").click();
  });
  <% end %>

     

app/views/lists/new.js.erb
$('#list-form').html("<%= j (render 'form',  :formats => :html) %>");
$('#list-content').html("<%= j (render 'form',  :formats => :html) %>");
$('#new_list_modal').openModal();
//legacy code
//$('#list-form').slideDown(350);

app/views/lists/update.js.erb
$('#lists').html("<%= j (render @lists) %>");
$('#new_list_modal').closeModal();
//$('#list-form').slideUp(350);
Materialize.toast('List Edited!', 4000)