config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :items
  resources :users
  resources :lists
  
  get 'main_pages/home' => 'main_pages#home', :as => :traversal_home
  get 'main_pages/list_results' => 'main_pages#city_search', :as => :city_search
  post 'main_pages/list_results' => 'main_pages#list_results'
  get 'main_pages/add_to_user' => "main_pages#add_to_user", :as => :add_to_user
  
  get 'main_pages/about_us' => 'main_pages#about_us', :as => :traversal_about_us
  get 'main_pages/contact_us' => 'main_pages#contact_us', :as => :traversal_contact_us
  
  resources :main_pages do
  get :autocomplete_city_name_and_cc, :on => :collection
  end

  root :to => 'main_pages#home'

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  autocomplete :city, :name_and_cc

  require 'open_weather'
  @team_page = false

  def add_to_user
    list = List.find(params[:list_id])
    items = list.items
    @list = list.dup
    @list.user_id = params[:user_id]
    @list.save
    items.each do |i|
      item = i.dup
      item.list_id = @list.id
      item.save
    end
    flash[:notice] = 'The official list is now added to your account!'
    redirect_to user_path(params[:user_id])
  end

  def home
    @html_title = "Traversal - Home"
  end

  def list_results
    @html_title = "Traversal - Results"

    @city = params[:city]
    @num_of_days = params[:duration]

    #@displayString = OpenWeather::Current.city(@city) Using openweather gem

    def find_by_city(city) #returns as a JSON
      #use HTTP to call random APIs using a query string
      HTTParty.get('http://api.openweathermap.org/data/2.5/weather', :query => {:q => city, :units => 'metric'})
    end

    def find_by_city_forecast(city, days)
      HTTParty.get('http://api.openweathermap.org/data/2.5/forecast', :query => {:q => city, :units => 'metric', :cnt => days})
    end

    def get_lat_long_by_city_name(city)
      Geocoder.coordinates(city)
    end

    #  puts find_by_city(@city).body #(shows up in the Rails server)
    weather_info = JSON.parse(find_by_city(@city).body)
    @displayString = weather_info["main"]["temp"].to_s + "°C"
    @displayString2 = weather_info["main"]["temp_min"].to_s + "°C"
    @displayString3 = weather_info["main"]["temp_max"].to_s + "°C"
    @weatherIcon = weather_info["weather"]
    @weatherIcon2 = @weatherIcon[0]["icon"]

    weather_forecast = JSON.parse(find_by_city_forecast(@city, 14).body)
    #puts find_by_city_forecast(@city,14).body
    #@displayForecast =  weather_forcast
    @displayForecastHash = weather_forecast["list"] #+ "°C"
    @displayForecastArray = []
    @displayForecastHash.each do |w|
      @displayForecastArray.push w["main"]["temp"]
    end

    @displayForecastArray2 = []
    @displayForecastHash.each do |v|
      @displayForecastArray2.push v["weather"][0]["icon"]
    end

    @lat_long = get_lat_long_by_city_name(@city)

    currentTemp = weather_info["main"]["temp"].to_f
    if currentTemp > '25.4'.to_f
      @season = 'Summer'.to_s
    elsif currentTemp < '14.4'.to_f
      @season = 'Winter'.to_s
    elsif currentTemp > '14.4'.to_f and currentTemp < '18.2'.to_f
      @season = 'Spring'.to_s
    else
      @season = 'Autumn'.to_s
    end

    #@season = @season.downcase
    @season_wrapper = "%"+@season+"%"

    @admin_user_id =  User.find_by( email: "admin@traversal.com").id
    @itemList = List.find_by('user_id = ? AND name LIKE ?', @admin_user_id, @season_wrapper).items.pluck(:name)
    
    @season_list = List.find_by('user_id = ? AND name LIKE ?', @admin_user_id, @season_wrapper)

    def find_image_by_city(city) #returns as a JSON
      #use HTTP to call random APIs using a query string
      HTTParty.get('https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=df3839f752aa839b3ea7e167b6f7394b&safe_search=1&per_page=10&page=1&format=json&nojsoncallback=1&tag_mode=AND', :query => {:tags => "#{city}&landscape"})
    end
    cityImage = JSON.parse(find_image_by_city(@city).body)
    @id = cityImage["photos"]["photo"].first["id"]
    @farmId = cityImage["photos"]["photo"].first["farm"]
    @secretId = cityImage["photos"]["photo"].first["secret"]
    @serverId = cityImage["photos"]["photo"].first["server"]

    @id2 = cityImage["photos"]["photo"].second["id"]
    @farmId2 = cityImage["photos"]["photo"].second["farm"]
    @secretId2 = cityImage["photos"]["photo"].second["secret"]
    @serverId2 = cityImage["photos"]["photo"].second["server"]

    @id3 = cityImage["photos"]["photo"].third["id"]
    @farmId3 = cityImage["photos"]["photo"].third["farm"]
    @secretId3 = cityImage["photos"]["photo"].third["secret"]
    @serverId3 = cityImage["photos"]["photo"].third["server"]

    @id4 = cityImage["photos"]["photo"].fourth["id"]
    @farmId4 = cityImage["photos"]["photo"].fourth["farm"]
    @secretId4 = cityImage["photos"]["photo"].fourth["secret"]
    @serverId4 = cityImage["photos"]["photo"].fourth["server"]

    @id5 = cityImage["photos"]["photo"].fifth["id"]
    @farmId5 = cityImage["photos"]["photo"].fifth["farm"]
    @secretId5 = cityImage["photos"]["photo"].fifth["secret"]
    @serverId5 = cityImage["photos"]["photo"].fifth["server"]


  end

  def about_us
    @html_title = "Traversal Team"
    @team_page = true
  end

  def contact_us
    @html_title = "Traversal Contact Us"
    @team_page = true
  end






end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/main_pages/about_us.html.erb
<div class="row about-us-heading-margin">
  <div class="col s12 center-align">
    <h1 class="red-text text-accent-1" style="font-weight: 600;"> We are the Traversies</h1>
    <h5>
      A team of two students from NUS, Majoring in Information Systems
      </h5>
    
  </div>
</div>

<div class="row grey lighten-4">
  <div class="col s12 l6 offset-l3 m6 offset-m3 center-align">
  <h3 class="red-text text-darken-1">
   Meet the team:
 </h3>
  </div>
</div>

<div class="row">
  <div class="col s6 center-align">
    <div class="col s6 offset-s3">
    <%= image_tag "ronald.jpg", class: "circle responsive-img" %>
        <br/>
  
    <h4>Ronald Kan</h4>
      <h6>A proficient gamer, coder and technology enthusiast</h6>
    </div>
  </div>
<div class="col s6 center-align">
    <div class="col s6 offset-s3">
    <%= image_tag "pohpeng.jpg", class: "circle responsive-img"%>
        <br/>
    <h4>Poh Peng, Ric</h4>
  <h6>An adventurer, coder and workaholic</h6>
  
    </div>
  </div>
</div>

<div class="row grey lighten-4">
  <div class="col s12 center-align">
  <h4 class="red-text text-darken-1">
   Want to talk to us? Refer to contact us above!
 </h4>
  </div>
</div>

app/views/main_pages/city_search.html.erb
  
  <div class="row center-align">
    <h3> Items to bring for  weather</h3>
    <ul>
      <% @cities.each do |i|%>
      <li>
        <h5>
        <%= i.name + " " + i.country_code %>
        </h5>
      </li>
      <% end %>
    </ul>
  </div>

app/views/main_pages/contact_us.html.erb
<!-- Services Section -->
  <section id="country_and_duration">
    <div class="container">
      <div class="col-lg-12 text-center">
          <h3 style="margin-top: 50px;"class="section-heading">Drop us a Message</h3>
          <div class="section-subheading text-muted">Have a question you'd like us to answer or feel like making an suggestions?
          <div>Simply contact us via the details below.</div>
          <div>We'd love to hear from you!</div></div>
          <div><a href="mailto:abc@gmail.com">feedback@traversal.com</a></div>
          <h5>Like us Facebook!</h5>
          <div class="fb-like" data-href="http://traversal.herokuapp.com/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
      </div>
    </div>
  </section>
  <!-- Portfolio Grid Section -->

app/views/main_pages/home.html.erb
<div id="mainBody">
  <!-- Services Section -->  
    <section id="country_and_duration">
      <div class="container">
        <div class="col s12 m8 l12 center-align">
            <h3 class="white-text">Travel Packing List Generator</h3>
            <h4 class="white-text">Enter your destination below.</h4>
        </div>
        <div class="row">
          <div class="col s12 m6 l6 offset-m3 offset-l3 center-align">
      <%=form_tag({controller: "main_pages", action: "list_results"}, method: "post") do%>
      
      <%= label_tag :city, nil, class: "white-text" %>
      <%= autocomplete_field_tag :city, nil, autocomplete_city_name_and_cc_main_pages_path, class: "white-text", placeholder: "Enter the City name", :autofocus => true, :required => true %>

      <%= label_tag :duration, nil, class: "white-text" %>
      <%= number_field_tag :duration, nil, min: 1, max: 21, step: 1, class: "white-text", placeholder: "Enter the number of days", :required => true %>
      <br/>
      <%= submit_tag "Submit", class: "btn btn-primary" %>
      
      <% end %>

          </div>
        </div>
      </div>
    </section>
</div>

app/views/main_pages/list_results.html.erb
<div class="owl-carousel">
  <div> <%= image_tag "https://farm#{@farmId}.staticflickr.com/#{@serverId}/#{@id}_#{@secretId}_b.jpg" %> </div>
  <div> <%= image_tag "https://farm#{@farmId2}.staticflickr.com/#{@serverId2}/#{@id2}_#{@secretId2}_b.jpg" %> </div>
  <div> <%= image_tag "https://farm#{@farmId3}.staticflickr.com/#{@serverId3}/#{@id3}_#{@secretId3}_b.jpg" %> </div>
  <div> <%= image_tag "https://farm#{@farmId4}.staticflickr.com/#{@serverId4}/#{@id4}_#{@secretId4}_b.jpg" %> </div>
  <div> <%= image_tag "https://farm#{@farmId5}.staticflickr.com/#{@serverId5}/#{@id5}_#{@secretId5}_b.jpg" %> </div>
</div>

<div class="col s12 center-align">
  <br/>
  <h2 class="">Weather Forecast Generated</h2>
  <h4 class="">Check your <%=@num_of_days%> days forecast below!</h4>
  <br/>
</div>


<div class="module-background white-text row grey darken-1">
  <ul class="weather_today center-align">
    <li>
      <h4>The Weather Today <%=Date.today%>  <%= image_tag "http://openweathermap.org/img/w/#{@weatherIcon2}.png" %> For:</h4>
      <%= @city %>
      <br/>
      <% image_tag "https://farm#{@farmId}.staticflickr.com/#{@serverId}/#{@id}_#{@secretId}_b.jpg" %>
      <br/>
    </li>
    <li>
      <h4>Season</h4>
      <%= @season%>
    </li>
    <li>
      <h4>Average temperature</h4>
      <%= @displayString %>
      <br/>
    </li>
    <li>
      <h4>Minimal temperature</h4>
      <%= @displayString2%>
      <br/>
    </li>
    <li>
      <h4>Maximum temperature</h4>
      <%= @displayString3%>
    </li>
  </ul>
</div>

<div class="clearer"></div>

</div>
<% if @num_of_days.to_i > 1 %>
<ul class="weather_forecast">
  <div class="row">
    <div class="col s12 l12 grey lighten-3 text-center">
      <li>
        <h4>The Weather Forecast For Next <%=@num_of_days%> days (Average Temperature Only): </h4>
      </li>
      
      <li>
      <div class="row">
        <% @displayForecastArray.each_with_index do |w, index|%>
        <div class="col s12 m6 l3">
          <h5>Day: <%=Date.today+(index+1).days%></h5>
          <%= image_tag "http://openweathermap.org/img/w/#{@displayForecastArray2[index]}.png" %>
          <%= w.to_s+'°C' %>
        </div>
        <% break if index == @num_of_days.to_i-2 #for logic number of days%>
        <% end %>
      </div>
      </li>

    </div>
  </div>
</ul>

<% end %>

<div class="row center-align">
  <h3> Items to bring for <%= @season%> weather </h3>
  <h1> </h1>
  <ul class="items_list">
    <% @itemList.to_a.each do |i|%>
    <li>
      <h5><%= i %></h5>
    </li>
    <% end %>
  </ul>
  <% if user_signed_in? %>
  <%= link_to "Add list to account", {:controller => "main_pages", :action => "add_to_user", :user_id => current_user.id, :list_id => @season_list.id } ,class: "btn" %>
  <% else %>
  <div class="card-panel grey lighten-3 info_user">
    <h2 class="blue-text text-darken-2"> Unhapppy with our generated list? Sign up now and create your own packing list! </h2>
  </div>
  <% end %>
</div>

<% content_for :script  do %>
var options = [
   {selector: '.weather_today', offset: 450, callback: 'Materialize.showStaggeredList(".weather_today")' },
   {selector: '.weather_forecast', offset: 300, callback: 'Materialize.showStaggeredList(".weather_forecast")' },
   {selector: '.items_list', offset: 300, callback: 'Materialize.showStaggeredList(".items_list")' },
   {selector: '.info_user', offset: 200, callback: '$(".info_user").fadeIn(2000)' }
 ];
 Materialize.scrollFire(options);
<% end %>