config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :items
  resources :users
  resources :lists
  
  get 'main_pages/home' => 'main_pages#home', :as => :traversal_home
  get 'main_pages/list_results' => 'main_pages#city_search', :as => :city_search
  post 'main_pages/list_results' => 'main_pages#list_results'
  get 'main_pages/add_to_user' => "main_pages#add_to_user", :as => :add_to_user
  
  get 'main_pages/about_us' => 'main_pages#about_us', :as => :traversal_about_us
  get 'main_pages/contact_us' => 'main_pages#contact_us', :as => :traversal_contact_us
  
  resources :main_pages do
  get :autocomplete_city_name_and_cc, :on => :collection
  end

  root :to => 'main_pages#home'

end

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <nav class="">
    <div class="nav-wrapper">
      <a href="<%= traversal_home_path%>" class="brand-logo center">Traversal</a>
      <a href="#" data-activates="mobile-traversal" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <li class="active"><a href="<%= traversal_home_path%>">Home</a></li>
        <li><a href="<%= traversal_about_us_path%>">About Us</a></li>
        <li><a href="<%= traversal_contact_us_path%>">Contact Us</a></li>
      </ul>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
           <li>
             <% if current_user.admin? %>
               <%= link_to 'Admin', admin_dashboard_path%>
             <% end %>
           </li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
          <li><strong><%=link_to current_user.email, user_path(id: current_user.id) %></strong></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %> </li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-traversal">
        <li class="active"><a href="<%= traversal_home_path%>">Home</a></li>
        <li><a href="<%= traversal_about_us_path%>">About Us</a></li>
        <li><a href="<%= traversal_contact_us_path%>">Contact Us</a></li>
        <hr/>
        <% if user_signed_in? %>
          <!-- <strong><%= current_user.email %></strong> -->
          <li>
            <% if current_user.admin? %>
              <%= link_to 'Admin', admin_dashboard_path%>
            <% end %>
          </li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
          <li><strong><%=link_to current_user.email, user_path(id: current_user.id) %></strong></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %> </li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      
    </div>
  </nav>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div id="home-flash" data-url="<%=value%>">
  </div>
  <script>
  var message = $("#home-flash").data('url');
  Materialize.toast(message, 4000);
   </script>
<% end %>

app/views/layouts/_team_header.html.erb
<div class="navbar-fixed">
<nav>
   <div class="nav-wrapper">
     <a href="#" class="brand-logo center">The Traversal Team</a>
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
     <ul id="nav-mobile" class="left hide-on-med-and-down">
       <li><a href="<%=traversal_home_path%>">Back to App</a></li>
       <li class="<%='active' if request.fullpath == "/main_pages/about_us" %>"><a href="<%=traversal_about_us_path%>">About Us</a></li>
       <li class="<%='active' if request.fullpath == "/main_pages/contact_us" %>"><a href="<%=traversal_contact_us_path%>">Contact Us</a></li>
     </ul>
     <ul class="side-nav" id="mobile-demo">
       <li><a href="<%=traversal_home_path%>">Back to App</a></li>
       <li class="<%='active' if request.fullpath == "/main_pages/about_us" %>"><a href="<%=traversal_about_us_path%>">About Us</a></li>
       <li class="<%='active' if request.fullpath == "/main_pages/contact_us" %>"><a href="<%=traversal_contact_us_path%>">Contact Us</a></li>
       </ul>
   </div>
 </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'favicon.ico'%>
  <title><%= !@html_title.blank? ? @html_title  : "Traversal" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <%= csrf_meta_tags %>
  <script src="//use.typekit.net/enm1ixs.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
</head>
<body>
  <div id="fb-root"></div>
  <% if !@team_page %>
    <%= render 'layouts/header' %>
  <% else %>
    <%= render 'layouts/team_header' %>
  <% end %>
   <%= render 'layouts/messages' %>
  <%= yield %>
</body>
<footer>
<script>
  $(document).ready(function(){
    
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=383718101838274";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    
    // Initialize collapse button
 $(".button-collapse").sideNav();
 $(".owl-carousel").owlCarousel(
  {
    autoPlay: 3000, // Show next and prev buttons
    slideSpeed : 300,
    paginationSpeed : 400,
    singleItem:true
  }
);
  <%= yield :script %>

 });


 </script>
</footer>
<%= debug(params) if Rails.env.development? %>
</html>